INSERT INTO USERVO (id, USER_ID, EMAIL, NAME, PASSWORD, CREATE_DATE) VALUES (1,'siaer','siaert@naver.com','강진영','siaer', CURRENT_TIMESTAMP());
INSERT INTO USERVO (id, USER_ID, EMAIL, NAME, PASSWORD, CREATE_DATE) VALUES (2, 'siaert','siaer00@naver.com','강진우','siaert', CURRENT_TIMESTAMP());

INSERT INTO QUESTIONVO (id,TITLE, CONTENTS, WRITER_ID, CREATE_DATE,count_of_answer) VALUES (1,'첫번째 테스트 글','1번째 테스트 글 내용',1, CURRENT_TIMESTAMP(), 0);
INSERT INTO QUESTIONVO (id,TITLE, CONTENTS, WRITER_ID, CREATE_DATE,count_of_answer) VALUES (2,'두번째 테스트 글','2번째 테스트 글 내용',2, CURRENT_TIMESTAMP(), 0);
INSERT INTO QUESTIONVO (id,TITLE, CONTENTS, WRITER_ID, CREATE_DATE,count_of_answer) VALUES (3,'세번째 테스트 글','3번째 테스트 글 내용',1, CURRENT_TIMESTAMP(), 0);
INSERT INTO QUESTIONVO (id,TITLE, CONTENTS, WRITER_ID, CREATE_DATE,count_of_answer) VALUES (4,'네번째 테스트 글','4번째 테스트 글 내용',2, CURRENT_TIMESTAMP(), 0);
INSERT INTO QUESTIONVO (id,TITLE, CONTENTS, WRITER_ID, CREATE_DATE,count_of_answer) VALUES (5,'다섯번째 테스트 글','5번째 테스트 글 내용',2, CURRENT_TIMESTAMP(), 0);
INSERT INTO QUESTIONVO (id,TITLE, CONTENTS, WRITER_ID, CREATE_DATE,count_of_answer) VALUES (6,'여섯번째 테스트 글','6번째 테스트 글 내용',1, CURRENT_TIMESTAMP(), 0);
INSERT INTO QUESTIONVO (id,TITLE, CONTENTS, WRITER_ID, CREATE_DATE,count_of_answer) VALUES (7,'칠곱번째 테스트 글','7번째 테스트 글 내용',2, CURRENT_TIMESTAMP(), 0);
INSERT INTO QUESTIONVO (id,TITLE, CONTENTS, WRITER_ID, CREATE_DATE,count_of_answer) VALUES (8,'여덞번째 테스트 글','8번째 테스트 글 내용',2, CURRENT_TIMESTAMP(), 0);
INSERT INTO QUESTIONVO (id,TITLE, CONTENTS, WRITER_ID, CREATE_DATE,count_of_answer) VALUES (9,'아홉번째 테스트 글','9번째 테스트 글 내용',1, CURRENT_TIMESTAMP(), 0);
INSERT INTO QUESTIONVO (id,TITLE, CONTENTS, WRITER_ID, CREATE_DATE,count_of_answer) VALUES (10,'열번째 테스트 글','10번째 테스트 글 내용',2, CURRENT_TIMESTAMP(), 0);
INSERT INTO QUESTIONVO (id,TITLE, CONTENTS, WRITER_ID, CREATE_DATE,count_of_answer) VALUES (11,'열한번번째 테스트 글','11번째 테스트 글 내용',1, CURRENT_TIMESTAMP(), 0);
INSERT INTO QUESTIONVO (id,TITLE, CONTENTS, WRITER_ID, CREATE_DATE,count_of_answer) VALUES (12,'열두번번째 테스트 글','12번째 테스트 글 내용',2, CURRENT_TIMESTAMP(), 0);
INSERT INTO QUESTIONVO (id,TITLE, CONTENTS, WRITER_ID, CREATE_DATE,count_of_answer) VALUES (13,'열세번번째 테스트 글','13번째 테스트 글 내용',2, CURRENT_TIMESTAMP(), 0);
INSERT INTO QUESTIONVO (id,TITLE, CONTENTS, WRITER_ID, CREATE_DATE,count_of_answer) VALUES (14,'열네번번째 테스트 글','14번째 테스트 글 내용',1, CURRENT_TIMESTAMP(), 0);
