INSERT INTO USERVO (id, USER_ID, EMAIL, NAME, PASSWORD) VALUES (1,'siaer','siaert@naver.com','강진영','siaer');
INSERT INTO USERVO (id, USER_ID, EMAIL, NAME, PASSWORD) VALUES (2, 'siaert','siaer00@naver.com','강진우','siaert');

INSERT INTO QUESTIONVO (id,TITLE, CONTENTS, WRITER_ID, CREATE_TIME) VALUES (1,'첫번째 테스트 글','첫번째 테스트 글 내용',1, CURRENT_TIMESTAMP());
INSERT INTO QUESTIONVO (id,TITLE, CONTENTS, WRITER_ID, CREATE_TIME) VALUES (2, '두번째 테스트 글','두번째 테스트 글 내용',2, CURRENT_TIMESTAMP());
